version: '3.8'

services:
  api:
    image: forex:development
    restart: on-failure
    command: sh scripts/start_api.sh
    environment:
      - DJANGO_ENV=development
      - DJANGO_PORT=8000
    volumes:
      - ../scripts:/code/scripts
      - ../src:/code/src
      - ../tests:/code/tests
  cache:
    restart: on-failure
    environment:
      - REDIS_PORT=6379
    volumes:
      - redisdata_development:/var/lib/redis/data
  db:
    restart: on-failure
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-forex}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    volumes:
      - pgdata_development:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d forex -U postgres
      interval: 10s
      timeout: 10s
      retries: 5
  worker:
    image: worker:development
    restart: on-failure
    command: sh scripts/start_worker.sh
    environment:
      - DJANGO_ENV=development
    volumes:
      - ../scripts:/code/scripts
      - ../src:/code/src
      - ../tests:/code/tests

volumes:
  pgdata_development:
    driver: local
    name: pgdata_development
  redisdata_development:
    driver: local
    name: redisdata_development
